### PR TITLE
Define OTA asserts to prevent recovery issues

### PR DESCRIPTION
**Pull request by FryUpDoe**

### CODE REVIEW

**Comment by 0x5ECF4ULT** [comment]
Regarding properties: I've pulled the relevant parts off the partitions and just `TARGET_<PARTITION>_PROPS`. Looks cleaner imo.

**Comment by 0x5ECF4ULT** [comment]
In other words: I'd revert https://github.com/0x5ECF4ULT/android_device_nothing_spacewar/pull/2/commits/a8b57873ed24d2d1de17856dd4a1177255faf92d

**Comment by FryUpDoe** [comment]
I'll move the USB one later but the rest are fine in testing, the display one being better for battery life instead of a constant 120hz. Asserts for recovery where mainly due to TWRP annoying the hell out of me yesterday. But yeah I'll revert

**Comment by 0x5ECF4ULT** [comment]
Your tree builds? Heck, I'm stuck on qcom-caf complaining. That may be due to stock kernel sources. Anyways, merging.

**Comment by FryUpDoe** [comment]
I've got a ton of uncommited changes locally, just pushing what I've tested is okay so far, then i'll start work on the lights on the back.

**Comment by 0x5ECF4ULT** [comment]
That sounds like pain. At least a userspace application needs to be written. If you want to collaborate a bit closer ping me on the LOS DC/IRC.

**Comment by FryUpDoe** [comment]
I've got a hook into settings for them but communicating with the driver isn't going to be fun, you can message me on DC if you want @FryUpDoe98#7082

**Pull request merged**
